name: AsureLib
version: 1.0
author: SaintQd
main: org.saintqd.asurelib.AsureLib
api-version: 26.2
softdepend:
  - Vault
  - PlaceholderAPI
  - DiscordSRV
  - MythicMobs
permissions:
  asurelib.admin:
    description: Access to admin commands.
    default: op